translatable_module.settings:
  type: config_object
  label: 'My module basic settings'
  mapping:
    title:
      label: 'Title'
      type: label
    message:
      label: 'Message'
      type: text
    ckeditor:
      label: 'Full Message'
      type: text_format